### ISSUE TITLE
not install. must match format 1.23 version

### ISSUE THREAD

**Issue by radist** [mattermost/migration-assist#2]
```
$ go install github.com/mattermost/migration-assist/cmd/migration-assist@latest
go: github.com/mattermost/migration-assist/cmd/migration-assist@latest (in github.com/mattermost/migration-assist@v0.0.0-20240715125416-f0acdc2712eb): go.mod:3: invalid go version '1.22.2': must match format 1.23
```

**Comment by ltsavar** [comment]
same here

**Comment by agnivade** [comment]
@radist - What is your Go version? I have 1.21.8 and it works fine.

**Comment by lkroll** [comment]
Using the `golang` package from Debian 12 I got the same error message when trying to install the migration-assistant.

Installing go 1.23 manually according to offical docs works however: https://go.dev/doc/install

**Comment by agnivade** [comment]
This has been open for a while without any response. Will go ahead and close it. Please let  me know if you are still facing issues.
