### ISSUE TITLE
Error "could not parse postgres connection string: no match found" after successful connection

### ISSUE THREAD

**Issue by TokkCorp** [mattermost/migration-assist#24]
When trying to create a postgres schema, I get the following output: 

```
sudo -u mattermost ./migration-assist postgres "postgres://mattermost@/mattermost?sslmode=disable" --run-migrations --
mattermost-version="v9.11.1"
2024-09-24 13:05:33 pinging postgres...
2024-09-24 13:05:33 connected to postgres successfully.
An Error Occurred: could not parse postgres connection string: no match found
```

**Comment by TokkCorp** [comment]
The Problem is the regex, I need a password and a port.

**Comment by agnivade** [comment]
Yes, please provide the password and port. We could have done better here, but this is just a one-off tool. Going ahead and closing this. Please let me know if you are still facing issues.

**Comment by lkraav** [comment]
0.4: Idk just ran into this, and with all due respect, requiring a very specific connection string is not great UX. At least this issue could be documented?
