### ISSUE TITLE
Migration for v10.0 - missing "RemoteClusters.deleteat" column

### ISSUE THREAD

**Issue by jangrewe** [mattermost/migration-assist#25]
When trying to migrate from MySQL to PostgreSQL, i get this error:

`$ pgloader migration.load > migration.log`
```
KABOOM!
SIMPLE-ERROR: pgloader failed to find column "mattermost"."RemoteClusters"."deleteat" in target table "\"mattermost\".\"remoteclusters\""
An unhandled error condition has been signalled:
   pgloader failed to find column "mattermost"."RemoteClusters"."deleteat" in target table "\"mattermost\".\"remoteclusters\""




What I am doing here?

pgloader failed to find column "mattermost"."RemoteClusters"."deleteat" in target table "\"mattermost\".\"remoteclusters\""
```

There is indeed no column `deleteat`, but there is `DeleteAt`.

I've followed this guide: https://docs.mattermost.com/deploy/postgres-migration-assist-tool.html

**Comment by isacikgoz** [comment]
Hey @jangrewe sorry I was on PTO and missed your issue. I think this column was added to the MySQL with `v10.1` so your target schema should be at that version. Can you verify that?

**Comment by jangrewe** [comment]
Thanks, i needed to do some additional fsckery because of issues with pgloader current_timestamp() single/double quote in the focalboard_blocks table, but it seems to work fine now (on version `10.1.3-rc1`, which is the current version of the `10.1` docker image, but not officially released - which isn't quite best practice, i'd say).

Anyways, i think i'm now successfully migrated to PostgreSQL, thanks! :-)
